"""Tests for per-testcase code workflow classification and batch persist."""

from __future__ import annotations

from web.gtest_workspace import (
    classify_generated_code_workflow,
    inject_testcase_id_comment,
    persist_batch_generation_error,
    persist_generated_draft_workflow,
)


def test_inject_testcase_id_comment() -> None:
    raw = "TEST_F(Fixture, test_name) { EXPECT_EQ(1, 1); }"
    out = inject_testcase_id_comment(raw, "TC_PM_001")
    assert "TC_PM_001" in out
    assert out.index("TC_PM_001") < out.index("TEST_F")


def test_classify_saved_good_code() -> None:
    code = inject_testcase_id_comment(
        "TEST_F(F, tc) { EXPECT_EQ(1, 1); }",
        "TC_PM_001",
    )
    wf = classify_generated_code_workflow(code, candidate_id="TC_PM_001")
    assert wf["code_status"] == "SAVED"
    assert wf["workflow_message"] == "generated by API"


def test_classify_needs_review_missing_expect() -> None:
    code = "// TC_PM_002\nTEST_F(F, tc) { }"
    wf = classify_generated_code_workflow(code, candidate_id="TC_PM_002")
    assert wf["code_status"] == "NEEDS_REVIEW"
    assert "EXPECT" in wf["workflow_message"]


def test_classify_error_empty() -> None:
    wf = classify_generated_code_workflow("", candidate_id="TC_PM_003")
    assert wf["code_status"] == "ERROR"


def test_persist_batch_saved_metadata() -> None:
    bundle = {
        "test_candidates": [{"id": "TC_PM_001"}],
        "ai_assists": {"candidate_overlays": {}},
    }
    gtest_state = {"drafts": {}, "harness": {}, "code_variable_map": {}}
    code = "// TC_PM_001\nTEST_F(F, tc) { EXPECT_EQ(1, 1); }"
    wf = persist_generated_draft_workflow(
        bundle,
        gtest_state,
        candidate_id="TC_PM_001",
        draft_payload={"full_snippet": code, "source_kind": "copilot"},
        generation_source="API",
        persist=True,
    )
    assert wf["code_status"] == "SAVED"
    saved = gtest_state["drafts"]["TC_PM_001"]
    assert saved["code_status"] == "SAVED"
    assert saved["generation_source"] == "API"
    assert saved.get("last_saved_at")


def test_persist_batch_error_placeholder() -> None:
    gtest_state = {"drafts": {}}
    persist_batch_generation_error(gtest_state, candidate_id="TC_X", error_message="API failed")
    assert gtest_state["drafts"]["TC_X"]["code_status"] == "ERROR"
